CREATE TABLE STATION (
  STATIONID VARCHAR(255) PRIMARY KEY,
  NAME      VARCHAR(255) NOT NULL,
  HDENABLED BOOLEAN NOT NULL,
  CALLSIGN  VARCHAR (255) NOT NULL
);

INSERT INTO STATION (STATIONID, NAME, HDENABLED, CALLSIGN) 
 VALUES
  ('STATION00', 'STATIONNAME00', TRUE, 'CALLSIGN00'),
  ('STATION01', 'STATIONNAME01', TRUE, 'CALLSIGN01'),
  ('STATION02', 'STATIONNAME02', FALSE, 'CALLSIGN02'),
  ('STATION03', 'STATIONNAME03', TRUE, 'CALLSIGN03'),
  ('STATION04', 'STATIONNAME04', FALSE, 'CALLSIGN04'),
  ('STATION05', 'STATIONNAME05', TRUE, 'CALLSIGN05');